a = input(); a = int(a)
if a < 0 or a > 99: print("Anda Menginput Melebihi Limit Bilangan")
elif a == 0: print("Nol")
elif a > 0 and a < 10: print("Satuan")
elif a == 10 or a > 19: print("Puluhan")
elif a > 10 and a < 20: print("Belasan")