print("##############################")
print("#                            #")
print("#   Sebastian Abe Santoso    #")
print("#        2410817210002       #")
print("#                            #")
print("##############################")