N = input  ("Nama                  : ")
NIM = input("NIM                   : ")
KP = input ("Kelas Paralel         : ")
TTL = input("Tempat/Tanggal Lahir  : ")
A = input  ("Alamat                : ")
H = input  ("Hobby                 : ")
NHP = input("No. HP                : ")
print("Nama                  :", N)
print("NIM                   :", NIM)
print("Kelas Paralel         :", KP)
print("Tempat/Tanggal Lahir  :", TTL)
print("Alamat                :", A)
print("Hobby                 :", H)
print("No. HP                :", NHP)